ArticleSearch/Models/SearchModel.cs
using Sitecore.ContentSearch;
using Sitecore.ContentSearch.SearchTypes;
using System.Collections.Generic;

namespace ArticleSearch.Models
{
    public class SearchModel : SearchResultItem
    {
        [IndexField("_name")]
        public virtual string ItemName { get; set; }

        [IndexField("author_t")]
        public virtual string Author { get; set; }

        [IndexField("description_t")]
        public virtual string Description { get; set; } // Custom field on my template

        [IndexField("title_t")]
        public virtual string Title { get; set; } // Custom field on my template
    }

    public class SearchResult
    {
        public string ItemName { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Description { get; set; }
    }

    /// <summary>
    /// Custom search result model for binding to front end
    /// </summary>
    public class SearchResults
    {
        public List<SearchResult> Results { get; set; }
    }
}

ArticleSearch/Controllers/ArticlesSearchController.cs
using ArticleSearch.Models;
using Sitecore.ContentSearch;
using Sitecore.ContentSearch.Linq;
using Sitecore.ContentSearch.Linq.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web.Mvc;

namespace ArticleSearch.Controllers
{
    public class ArticlesSearchController : Controller
    {
        // GET: ArticlesSearch
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ArticlesComponent()
        {
            var item = Sitecore.Context.Database.GetItem("{D9D1CEF1-72A6-42D8-A078-1C46E05D9E13}");
            string str = item.Fields["Copyright"].Value;
            // Logic
            // Debugging - Being The Detective In a Crime Movie Where You Are Also The Murderer.
            return View("~/Views/Articles/2021/Jun/Body.cshtml", item);
        }
        public ActionResult DoSearch(string searchText)
        {
            var myResults = new SearchResults
            {
                Results = new List<SearchResult>()
            };
            var searchIndex = ContentSearchManager.GetIndex("sitecore_web_index"); // Get the search index
            var searchPredicate = GetSearchPredicate(searchText); // Build the search predicate
            using (var searchContext = searchIndex.CreateSearchContext()) // Get a context of the search index
            {
                //Select * from Sitecore_web_index Where Author="searchText" OR Description="searchText" OR Title="searchText"
                //var searchResults = searchContext.GetQueryable<SearchModel>().Where(searchPredicate); // Search the index for items which match the predicate
                var searchResults = searchContext.GetQueryable<SearchModel>()
                    .Where(x => x.Author.Contains(searchText) || x.Title.Contains(searchText) || x.Description.Contains(searchText));   //LINQ query

                var fullResults = searchResults.GetResults();

                // This is better and will get paged results - page 1 with 10 results per page
                //var pagedResults = searchResults.Page(1, 10).GetResults();
                foreach (var hit in fullResults.Hits)
                {
                    myResults.Results.Add(new SearchResult
                    {
                        Description = hit.Document.Description,
                        Title = hit.Document.Title,
                        ItemName = hit.Document.ItemName,
                        Author = hit.Document.Author
                    });
                }
                return new JsonResult { JsonRequestBehavior = JsonRequestBehavior.AllowGet, Data = myResults };
            }
        }

        /// <summary>
        /// Search logic
        /// </summary>
        /// <param name="searchText">Search term</param>
        /// <returns>Search predicate object</returns>
        public static Expression<Func<SearchModel, bool>> GetSearchPredicate(string searchText)
        {
            var predicate = PredicateBuilder.True<SearchModel>(); // Items which meet the predicate
                                                                  // Search the whole phrase - LIKE
                                                                  // predicate = predicate.Or(x => x.DispalyName.Like(searchText)).Boost(1.2f);
                                                                  // predicate = predicate.Or(x => x.Description.Like(searchText)).Boost(1.2f);
                                                                  // predicate = predicate.Or(x => x.Title.Like(searchText)).Boost(1.2f);
                                                                  // Search the whole phrase - CONTAINS
            predicate = predicate.Or(x => x.Author.Contains(searchText)); // .Boost(2.0f);
            predicate = predicate.Or(x => x.Description.Contains(searchText)); // .Boost(2.0f);
            predicate = predicate.Or(x => x.Title.Contains(searchText)); // .Boost(2.0f);
            //Where Author="searchText" OR Description="searchText" OR Title="searchText"
            return predicate;
        }
    }
}

ArticleSearch/Views/Articles/2021/Jun/Body.cshtml
@{
	var item = Sitecore.Context.Database.GetItem("{F5CC3E04-72D8-4B24-8D9F-8026494D51B0}");
}

@{
	var item1 = Sitecore.Context.Database.GetItem("{AF6A94CA-1F9C-449A-92EF-1B4DA5200538}");
}

@{
	var item2 = Sitecore.Context.Database.GetItem("{4C67E566-D359-43CA-B985-52217BBF59BE}");
}

@{
	var item3 = Sitecore.Context.Database.GetItem("{E4B3CCCC-6BD3-4F0C-AE34-37B1AF7E9D51}");
}

@{
	var item4 = Sitecore.Context.Database.GetItem("{49DC83E5-60F9-4EF0-AA90-311D2DCDEC81}");
}

<div class="row">
	<div class="blog-post-card card col-lg-4">
		@Html.Sitecore().Field("ArticleSamllImage")
		<div class="card-body bg-light">
			<strong class="d-inline-block mb-2 text-success">Design</strong>
			<h3>@Html.Sitecore().Field("title") </h3>
			<div class="mb-1 text-muted">@Html.Sitecore().Field("posteddate", new { format = "MMM\ndd,\nyyyy" })</div>	
			<p>@Html.Sitecore().Field("ShortDescription")</p>					
			<a href="articlesblog" target="_blank" class="btn btn-warning btn-block">@Html.Sitecore().Field("PostCardButtonText", item)</a>				
		</div>		
	</div>	

	<div class="blog-post-card card col-lg-4">
		@Html.Sitecore().Field("ArticleSamllImage", item1)		
		<div class="card-body bg-light">
			<strong class="d-inline-block mb-2 text-success">Design</strong>
			<h3>@Html.Sitecore().Field("title", item1) </h3>
			<div class="mb-1 text-muted">@Html.Sitecore().Field("posteddate", item1, new { format = "MMM\nd,\nyyyy" })</div>	
			<p>@Html.Sitecore().Field("ShortDescription", item1)</p>					
			<a href="articlesblog" target="_blank" class="btn btn-warning btn-block">@Html.Sitecore().Field("PostCardButtonText", item)</a>				
		</div>		
	</div>

	<div class="blog-post-card card col-lg-4">
		@Html.Sitecore().Field("ArticleSamllImage", item2)		
		<div class="card-body bg-light">
			<strong class="d-inline-block mb-2 text-success">Design</strong>
			<h3>@Html.Sitecore().Field("title", item2) </h3>
			<div class="mb-1 text-muted">@Html.Sitecore().Field("posteddate", item2, new { format = "MMM\ndd,\nyyyy" })</div>	
			<p>@Html.Sitecore().Field("ShortDescription", item2)</p>					
			<a href="articlesblog" target="_blank" class="btn btn-warning btn-block">@Html.Sitecore().Field("PostCardButtonText", item)</a>			
		</div>		
	</div>		
</div>	

<div class="row">
	<div class="blog-post-card card col-lg-4">
		@Html.Sitecore().Field("ArticleSamllImage", item3)		
		<div class="card-body bg-light">
			<strong class="d-inline-block mb-2 text-success">Design</strong>
			<h3>@Html.Sitecore().Field("title", item3) </h3>
			<div class="mb-1 text-muted">@Html.Sitecore().Field("posteddate", item3, new { format = "MMM\ndd,\nyyyy" })</div>	
			<p>@Html.Sitecore().Field("ShortDescription", item3)</p>					
			<a href="articlesblog" target="_blank" class="btn btn-warning btn-block">@Html.Sitecore().Field("PostCardButtonText", item)</a>			
		</div>		
	</div>
	
	<div class="blog-post-card card col-lg-4">
		@Html.Sitecore().Field("ArticleSamllImage", item4)		
		<div class="card-body bg-light">
			<strong class="d-inline-block mb-2 text-success">Design</strong>
			<h3>@Html.Sitecore().Field("title", item4) </h3>
			<div class="mb-1 text-muted">@Html.Sitecore().Field("posteddate", item4, new { format = "MMM\ndd,\nyyyy" })</div>	
			<p>@Html.Sitecore().Field("ShortDescription", item4)</p>					
			<a href="articlesblog" target="_blank" class="btn btn-warning btn-block">@Html.Sitecore().Field("PostCardButtonText", item)</a>				
		</div>		
	</div>
</div>	
	

ArticleSearch/Views/Articles/2021/Jun/Detail.cshtml
@{
	var item = Sitecore.Context.Database.GetItem("{42640601-8106-4A29-9F1A-5D1BD9E7EEDC}");
}

@{
	var item1 = Sitecore.Context.Database.GetItem("{1E8430B4-1A0E-4509-9DF2-2325C565E18B}");
}

<div class="row">
	<div class="blog-post-detail-card card col-lg-12">
		@Html.Sitecore().Field("ArticleLargeImage", item)		
		<div class="card-body bg-light">
			<strong class="d-inline-block mb-2 text-success">Design</strong>
			<h3>@Html.Sitecore().Field("title", item) </h3>
			<div class="mb-1 text-muted">@Html.Sitecore().Field("posteddate", new {format="MMM\ndd,\nyyyy"})</div>				
			<p>@Html.Sitecore().Field("LongDescription", item)</p>

			<div class="blog-detail-tag-list"><span class="read-more-heading">Read more: </span>			
				<a class="btn btn-info" role="button">@Html.Sitecore().Field("TagName", item1)</a>
				<a class="btn btn-info" role="button">@Html.Sitecore().Field("TagDescription", item1)</a>
				<a class="btn btn-info" role="button">@Html.Sitecore().Field("TagName", item1)</a>
			</div>
		</div>		
	</div>		
</div>	

ArticleSearch/Views/Articles/2021/Jun/DetailLayout.cshtml
@using Sitecore.Mvc
@using Sitecore.Mvc.Analytics.Extensions
@{
	Layout = null;
}



<html>
	<head>
	
	<title>Sitecore Powered Blog</title>
	
	<link rel="stylesheet" href="~/assets/css/bootstrap-themed.min.css">
	
	<script src="~/assets/js/jquery.min.js"></script>
	<script src="~/assets/js/bootstrap.bundle.js"></script>

	</head>
	<body>		
	<div class="container">	
		@Html.Sitecore().Placeholder("phMain")
	</div>		
	</body>	
</html>

ArticleSearch/Views/Articles/2021/Jun/Footer.cshtml
@{
    //var item = Sitecore.Context.Database.GetItem("/sitecore/content/Home/Alud/Setting/GlobalSetting");
    var item = Sitecore.Context.Database.GetItem("{F5CC3E04-72D8-4B24-8D9F-8026494D51B0}");
}

<Footer>
    
		<div class="text-white bg-primary">
			<p class="lead">@Html.Sitecore().Field("Copyright", item)<p>
		</div>
	
</Footer>

ArticleSearch/Views/Articles/2021/Jun/Header.cshtml
@{
    //var item = Sitecore.Context.Database.GetItem("/sitecore/content/Home/Alud/Setting/GlobalSetting");
    var item = Sitecore.Context.Database.GetItem("{F5CC3E04-72D8-4B24-8D9F-8026494D51B0}");
}

<header>	
	<div class="jumbotron text-white bg-primary">
		<h1 class="display-3">@Html.Sitecore().Field("Header-Title", item)<h1>
		<p class="lead">@Html.Sitecore().Field("Header Sub Title", item)<p>
	</div>	
</header>

ArticleSearch/Views/Articles/2021/Jun/MasterLayout.cshtml
@using Sitecore.Mvc
@using Sitecore.Mvc.Analytics.Extensions
@{
	Layout = null;
}



<html>
	<head>
	
	<title>Sitecore Powered Blog</title>

	<link rel="stylesheet" href="~/assets/css/bootstrap-themed.min.css">
	<link rel="stylesheet" href="~/assets/css/blogsite.css">
	<script src="~/assets/js/jquery.min.js"></script>
	<script src="~/assets/js/bootstrap.bundle.js"></script>

	</head>
	<body>		
	<div class="container">	
		@Html.Sitecore().Placeholder("phMain")
	</div>		
	</body>	
</html>

ArticleSearch/Views/Articles/2021/Jun/Search.cshtml
@{
    ViewBag.Title = "SOLR Search Component";
}

<!-- <h2>Search Item</h2> -->

<div class="form-example">
	<main role="main" class="container blog-posts">
	
	<div class="main-search">
		<div class="input-group">
			<input type="text" name="name" id="searchInput" placeholder="Search this blog" class="form-control" required>		
			<div class="input-group-append">
				<button class="btn btn-dark" type="button" id="searchButton">
					Search
				</button>
			</div>
		</div>
	</div>
</div>


<div id="resultsItem"></div>

<script>
		$(document).ready(function () {
			$("#searchButton").click(function (e) {
				// debugger;
				//alert('Test');
				e.preventDefault();
				$.ajax({
				
					type: "GET",
					datatype: "JSON", url: "@Url.Action("DoSearch", "ArticlesSearch")",
					contentType: "application/json",
					data: {
						searchText: $("#searchInput").val()
					},
					success: function (result) {
						var resultText = "";
						$('#resultsItem').text(resultText);
						$('#resultsItem').append("Results from SOLR index <BR><BR>");
						$(result.Results).each(function (index, item) {
							// each iteration
							var Description = item.Description;
							var Title = item.Title;
							var Author = item.Author;
							var ItemName = item.ItemName;
							resultText += (index + 1) + " - " + ItemName + Title + "; " + Author + "; " + Description + "; " + "<BR><BR>";
						});
						$('#resultsItem').append(resultText);
					},
					error: function (result) {
						alert('error');
					}
				});
			});
		});
</script>